import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Appbar } from "../components/Appbar";
import SubAppbar from "../components/SubAppbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Market",
  description: "Generated by create next app",
};

export default function MarketsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
        <SubAppbar/>
        {children}
    </div>
  );
}
