apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-frontend
  namespace: cryptex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto
  template:
    metadata:
      labels:
        app: crypto
    spec:
      containers:
        - name: crypto-frontend
          image: crypto-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-frontend-service
spec:
  selector:
    app: crypto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30080
  type: NodePort