
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthInspector } from "./utils/AuthInspector";
import { Appbar } from "./components/Appbar";
import ToastProvider from "./toaster-provider";
import { UserProvider } from "./utils/context/UserProvider";
import ClientLayout from "./utils/context/ClientLayout";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>
        <Appbar />
        <ToastProvider/>
        {children}

        </ClientLayout>
      </body>
    </html>
  );
}
