version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: shivansh
      POSTGRES_PASSWORD: shamsher@54
    volumes:
      - timescale-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgresdb:
    image: postgres
    container_name: postgresdb
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: shivansh
      POSTGRES_PASSWORD: shamsher@54
    volumes:
      - postgres-data:/var/lib/postgresql/data
  

volumes:
  timescale-data:
  postgres-data:
