apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-api
  namespace: cryptex
spec:
  replicas: 1 
  selector:
    matchLabels:
        app: crypto
  template: 
    metadata:
      labels:
        app: crypto
    spec:
      containers:
        - name: crypto-api
          image: crpto-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-api-service
spec:
  selector:
    app: crypto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30081
  type: NodePort
